cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    guest:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: guest
      password: $2b$12$t80AisinKXzJiHhu9JYyr.HdA845YDo0mHNX3CJ.ys34tqh05Wu1C
    sunny:
      email: sunny@mail.com
      failed_login_attempts: 0
      logged_in: false
      name: Sunny
      password: $2b$12$sPIjCHMCW/d6ovsQpQm7mOpeRR4jjwVK4AeThq4UwOe5WlhECyElq
    tester1:
      email: null
      failed_login_attempts: 0
      logged_in: true
      name: tester 1
      password: $2b$12$iWlVOac3uujRvTrXDi6wructXftKmo/GyQd6SMu5FmyX306kH.yFO
    tester2:
      email: null
      failed_login_attempts: 0
      logged_in: false
      name: tester 2
      password: $2b$12$uNaTgvGPG9rMbzOJHYaPQePw0DUfp1qHBrSq6l4O304qani6pKFpm
pre-authorized:
  emails:
  - corcortes@gmail.com
